In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns 
import sklearn 
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from matplotlib.colors import ListedColormap
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report,confusion_matrix
%matplotlib inline

import warnings

warnings.filterwarnings('ignore')

In [3]:
data=pd.read_csv(r'C:\Users\bloom\OneDrive\Desktop\New folder\DMDW\6 class csv.csv')

In [4]:
data.shape

(240, 7)

In [5]:
data.head()


Temperature   Luminosity  Radius  Absolutemagnitude  Startype Starcolor  \
0          3068    0.002400  0.1700              16.12         0       Red   
1          3042    0.000500  0.1542              16.60         0       Red   
2          2600    0.000300  0.1020              18.70         0       Red   
3          2800    0.000200  0.1600              16.65         0       Red   
4          1939    0.000138  0.1030              20.06         0       Red   

  SpectralClass  
0             M  
1             M  
2             M  
3             M  
4             M

In [6]:
data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Temperature        240 non-null    int64  
 1   Luminosity         240 non-null    float64
 2   Radius             240 non-null    float64
 3   Absolutemagnitude  240 non-null    float64
 4   Startype           240 non-null    int64  
 5   Starcolor          240 non-null    object 
 6   SpectralClass      240 non-null    object 
dtypes: float64(3), int64(2), object(2)
memory usage: 13.2+ KB


In [27]:
data = data.drop("Starcolor", axis=1)

In [28]:
x=data.drop('SpectralClass',axis=1)
y=data['SpectralClass']

In [29]:
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size = 0.30, random_state = 17)

In [30]:
model=GaussianNB()


In [31]:
model.fit(X_train,y_train)

GaussianNB()

In [32]:
predictions=model.predict(X_test)

In [34]:
print(confusion_matrix(y_test,predictions))
print('\n')
print(classification_report(y_test,predictions))

[[ 5  0  0  0  0  0  2]
 [ 0  5  5  0  0  0  3]
 [ 0  0  9  0  0  0  0]
 [ 0  0  0  0  0  0  1]
 [ 0  0  1  0  0  1  0]
 [ 0  0 25  0  0  5  0]
 [ 0  1  0  0  0  0  9]]


              precision    recall  f1-score   support

           A       1.00      0.71      0.83         7
           B       0.83      0.38      0.53        13
           F       0.23      1.00      0.37         9
           G       0.00      0.00      0.00         1
           K       0.00      0.00      0.00         2
           M       0.83      0.17      0.28        30
           O       0.60      0.90      0.72        10

    accuracy                           0.46        72
   macro avg       0.50      0.45      0.39        72
weighted avg       0.71      0.46      0.44        72

